---
title: "02_disease_profiling"
output: html_document
autor: "María Bueno Álvez"
date: "2024-12-13"
editor_options: 
  chunk_output_type: console
---

# Set up

```{r}
source("scripts/functions/functions_analyses.R")
source("scripts/functions/functions_utility.R")
source("scripts/functions/functions_visualization.R")
source("scripts/functions/themes_palettes.R")

# Read in data
data_disease <- read_tsv("../Human-disease-blood-atlas/data/final_data/HPA/v24_2/disease_data_phase1.tsv")
meta_disease <- read_tsv("../Human-disease-blood-atlas/data/final_data/HPA/v24_2/disease_meta_phase1.tsv")
```

## Disease order

```{r}
disease_class_order <-
  meta_disease |> 
  distinct(Class, Disease) |> 
  mutate(Class = factor(Class, levels = class_order)) |> 
  arrange(Class, Disease) |> 
  pull(Disease)

# Exclude diseases with more than 50 samples for machine learning
exclude_diseases <- 
  meta_disease |>
  filter(DAid %in% data_disease$DAid) |>
  count(Disease) |> 
  arrange(n) |> 
  filter(n < 48) |> 
  pull(Disease)

include_diseases <- 
  meta_disease |>
  distinct(Disease) |> 
  filter(!Disease %in% c(exclude_diseases, "Healthy")) |> 
  pull(Disease)

disease_class_order_ml <-
  meta_disease |> 
  distinct(Class, Disease) |> 
  filter(Disease %in% include_diseases) |> 
  mutate(Class = factor(Class, levels = class_order)) |> 
  arrange(Class, Disease) |> 
  pull(Disease)
```

## Prepare data

```{r}
ml_data <- 
  data_disease |>
  left_join(meta_disease |> 
              select(DAid, Disease, Class), by = "DAid") |> 
  filter(Disease %in% c(include_diseases, "Healthy")) |> 
  select(DAid, Disease, Assay, NPX) |> 
  pivot_wider(names_from = Assay,
              values_from = NPX) 


# Split data 100 times
seeds <- c(1:100)
random_splits <-
  map(seeds, \(seed) generate_split(data = ml_data,
                                    proportion = 0.7,
                                    variable_stratify = "Disease",
                                    seed = seed))

#saveRDS(random_splits, "server-scripts/data/random_splits.rds")
```

## Import parsed results from cluster 

```{r}
# Importances
importances_all <- read_tsv("server-scripts/parsed-results/importances_disease_all.tsv")
importances_class <- read_tsv("server-scripts/parsed-results/importances_disease_class.tsv")
importances_healthy <- read_tsv("server-scripts/parsed-results/importances_disease_healthy.tsv")

# Performance
predictions_all <- read_tsv("server-scripts/parsed-results/predictions_disease_all.tsv")
predictions_class <- read_tsv("server-scripts/parsed-results/roc_disease_class.tsv")
predictions_healthy <- read_tsv("server-scripts/parsed-results/roc_disease_healthy.tsv")

# ROC
roc_all <- read_tsv("server-scripts/parsed-results/roc_disease_all.tsv")
roc_class <- read_tsv("server-scripts/parsed-results/roc_disease_class.tsv")
roc_healthy <- read_tsv("server-scripts/parsed-results/roc_disease_healthy.tsv")
```

## Feature importance

# Combine

```{r}
scaled_healthy <- 
  importances_healthy |> 
  select(Disease = Class, Control = Type, Seed, Assay = Variable, Importance) |> 
  group_by(Disease, Seed) |> 
  mutate(Importance = scales::rescale(Importance, to = c(0,100))) |> 
  filter(Importance != 0)

class_scaling <- 
  importances_class |> 
  distinct(Disease = class, Seed) |> 
  mutate(Importance = 0,
         Assay = "SCALING")

scaled_class <- 
  importances_class |> 
  select(Disease = class, Control = Type, Seed, Assay = term, Importance = estimate) |> 
  mutate(Importance = abs(Importance)) |> 
  bind_rows(class_scaling) |> 
  group_by(Disease, Seed) |> 
  mutate(Importance = scales::rescale(Importance, to = c(0,100))) |> 
  filter(Assay != "SCALING")

all_scaling <- 
  importances_all |> 
  distinct(Disease = class, Seed) |> 
  mutate(Importance = 0,
         Assay = "SCALING")

scaled_all <- 
  importances_all |> 
  select(Disease = class, Control = Type, Seed, Assay = term, Importance = estimate) |>
  mutate(Importance = abs(Importance)) |> 
  bind_rows(class_scaling) |> 
  group_by(Disease, Seed) |> 
  mutate(Importance = scales::rescale(Importance, to = c(0,100))) |> 
  filter(Assay != "SCALING")
```

# Save for HPA

```{r}
final_importance_data  <- 
  scaled_healthy |> 
  bind_rows(scaled_class) |>
  bind_rows(scaled_all) |> 
  left_join(data_disease |> 
                distinct(Assay, OlinkID), by = "Assay") |> 
  relocate(OlinkID, .after = Assay) |> 
  mutate(Disease = factor(Disease, levels = disease_class_order),
         Control = factor(Control, levels = c("All other diseases", "Class", "Healthy"))) |> 
  arrange(Control, Disease, Seed, -Importance)

#write_csv(final_importance_data, savepath_data("Supplementary-files", "final_importances.csv"))
#write_csv(final_importance_data, "../Human-disease-blood-atlas/data/final_data/HPA/v24_2/disease_ml.csv")
```


# Protein importances

```{r}
plots_features <- 
  map(include_diseases, function(disease) {
    
    dat <- 
  final_importance_data |> 
  filter(Disease == disease) 

top10 <- 
  dat |> 
  group_by(Control, Assay) |> 
  summarise(n = n_distinct(Seed),
            avg_importance = mean(Importance)) |> 
  filter(n > 20) |> 
  arrange(-avg_importance) |> 
  top_n(10) |> 
  distinct(Control, Assay, avg_importance) 

dat |> 
  left_join(meta_disease |> 
              distinct(Disease, Class), by = "Disease") |>
  inner_join(top10, by = c("Control", "Assay")) |>
  group_by(Control) |> 
  mutate(Assay = reorder_within(Assay, avg_importance, Control)) |> 
  ggplot(aes(Importance, Assay, color = Class)) +
  geom_quasirandom(show.legend = F) +
  geom_boxplot(fill = NA, outlier.color = NA, show.legend = F) + 
  scale_y_reordered() +
  scale_color_manual(values = pal_class) +
  facet_wrap(~Control, scales = "free") +
  theme_hpa() +
  ggtitle(disease)
  
})
```


## Protein importance for example diseases

```{r}
importances_all  |> 
  distinct(class) |> 
  filter(!class %in% include_diseases)

example_diseases <- c("Acute myeloid leukemia",
                      "Influenza",
                      "Acute coronary syndrome",
                      "Rheumatoid arthritis",
                      "Viral hepatitis related cirrhosis", 
                      "Schizophrenia")

importances_all |> 
  mutate(class = ifelse(class == "Scleroderma", "Systemic sclerosis", class)) |> 
  group_by(class, term) |> 
  summarise(avg_estimate = mean(estimate)) |> 
  group_by(class) |> 
  top_n(n = 20, wt = abs(avg_estimate)) |> 
  arrange(class, avg_estimate) |> 
  mutate(Names = paste(class, avg_estimate)) |> 
  left_join(meta_disease |> 
              distinct(Disease, Class), by = c("class" = "Disease")) |> 
  filter(class %in% example_diseases) |> 
  #filter(class != "Healthy") |> 
 # mutate(class = factor(class, levels = disease_class_order[disease_class_order %in% include_diseases])) |> 
  ggplot(aes(fct_reorder(Names, -avg_estimate), avg_estimate, color = Class)) + 
  geom_point(show.legend = F) + 
  geom_segment(aes(x = Names, xend = Names, y = 0, yend = avg_estimate), show.legend = F) + 
  geom_text(aes(label = term), show.legend = F, angle = 90, size = 2) + 
  geom_hline(yintercept = 0) + 
  facet_wrap(~class, scales = "free_x", nrow = 1) + 
  scale_color_manual(values = pal_class) + 
  xlab("") + 
  theme_hpa(axis_x = F)

ggsave(savepath("features-multiclass.pdf"), h = 3, w = 12)
```


## Number important features

```{r}
final_importance_data |>
  group_by(Control, Disease, Seed) |> 
  summarize(n = n_distinct(Assay)) |> 
  left_join(meta_disease |> 
              distinct(Disease, Class), by = "Disease") |>
  mutate(Disease = factor(Disease, levels = disease_class_order)) |> 
  ggplot(aes(Disease, n, color = Class, fill = Class)) +
  geom_quasirandom(size = 0.5) +
  geom_boxplot(width = 0.5, outlier.color = NA, color = "grey20", alpha = 0.5) +
  facet_wrap(~Control, ncol = 1, scales = "free_y") +
  scale_color_manual(values = pal_class) + 
  scale_fill_manual(values = pal_class) + 
  theme_hpa(angled = T)
```

## Number of time a feature is selected

```{r}
final_importance_data |>
  group_by(Control, Disease, Assay) |> 
  summarize(n = n_distinct(Seed)) |> 
  left_join(meta_disease |> 
              distinct(Disease, Class), by = "Disease") |>
  mutate(Disease = factor(Disease, levels = disease_class_order)) |> 
  ggplot(aes(Disease, n, color = Class, fill = Class)) +
  geom_quasirandom(size = 0.5) +
  geom_boxplot(width = 0.5, outlier.color = NA, color = "grey20", alpha = 0.5) +
  facet_wrap(~Control, ncol = 1, scales = "free_y") +
  scale_color_manual(values = pal_class) + 
  scale_fill_manual(values = pal_class) + 
  theme_hpa(angled = T)
```

## Example diseases

```{r}
example_diseases <- c("Rheumatoid arthritis",
                      "Acute venous thromboembolism",
                      "Schizophrenia",
                      "MASLD", 
                      "Malaria")

imp_plots <- 
  map(example_diseases, \(disease) {
    
    imp <- 
      multiclass_importance |> 
      filter(class == disease)
    
    current_class <- 
      resource_meta |> 
      filter(Disease == disease) |> 
      pull(Class) |> 
      unique()
    
    plot_top_proteins_seed(imp, 
                           plot_color = pal_class[[current_class]],
                           n = 10) +
      ggtitle(disease) 
  })

imp_plots[[1]] / imp_plots[[2]] / imp_plots[[3]] / imp_plots[[4]] / imp_plots[[5]] 
ggsave(savepath("features_selected_diseases.pdf"), h = 16, w = 4)
```

# Performance


### Plot AUC comparison

```{r}
combined_auc <- 
  roc_class |> 
  distinct(Disease = Group, Seed, AUC) |> 
  mutate(Control = "Class") |> 
  bind_rows(roc_all|> 
              distinct(Disease = Group, Seed, AUC)|> 
              mutate(Control = "All other diseases")) |> 
  bind_rows(roc_healthy|>
              distinct(Disease = Class, Seed, AUC)|> 
              mutate(Control = "Healthy")) |> 
  mutate(Disease = factor(Disease, levels = disease_class_order)) |> 
  arrange(Disease, Seed)


all_summary <- 
  combined_auc |> 
  group_by(Control, Disease) |> 
  summarise(mean_auc = mean(AUC),
            sd_auc = sd(AUC)) |> 
  left_join(meta_disease |> 
              distinct(Disease, Class)) |> 
  mutate(Disease = factor(Disease, levels = disease_class_order),
         Class = factor(Class, levels = class_order)) |> 
  arrange(Disease)

all_summary |> 
 # mutate(Disease = factor(Disease, levels = disease_class_order)) |> 
  ggplot(aes(Disease, mean_auc, color = Control)) +
  geom_point() +
  geom_segment(aes(x = Disease, xend = Disease, 
                   y = mean_auc - sd_auc, 
                   yend = mean_auc + sd_auc)) +
  scale_color_manual(values = pal_controls) +
  facet_grid(~Class, scales = "free_x", space = "free") +
  theme_hpa(angled = T)

ggsave(savepath_results("Manuscript-figures", "auc_comparison.pdf"), width = 12, height = 5)
```

## Save performance

```{r}
final_performance_data <- 
  combined_auc |> 
  mutate(Disease = factor(Disease, levels = disease_class_order),
         Control = factor(Control, levels = c("All other diseases", "Class", "Healthy"))) |> 
  arrange(Control, Disease, Seed)

write_csv(final_performance_data, savepath_data("Supplementary-files", "final_performance.csv"))
```


## Plot confusion matrix

```{r}
predictions_all |> 
  mutate(Disease = factor(Disease),
         .pred_class = factor(.pred_class)) |>
  conf_mat(truth = Disease, estimate = .pred_class)  |> 
  plot_cm(percentage = T) 

ggsave(savepath_results("Manuscript-figures", "confusion_matrix_multiclass.pdf"), width = 10, height = 10)
```


