---
title: "04_validation"
output: html_document
autor: "María Bueno Álvez"
date: "2024-12-13"
editor_options: 
  chunk_output_type: console
---

# Set up

```{r}
source("scripts/functions/functions_analyses.R")
source("scripts/functions/functions_utility.R")
source("scripts/functions/functions_visualization.R")
source("scripts/functions/themes_palettes.R")

# Read in data - UKB
ukb_data <- read_delim("data/UKBB_cancer_olink.txt")

ukb_meta <- read_delim("data/UKBB_cancer_meta.txt")
ukb_meta <-
  ukb_meta |> 
  distinct(eid, .keep_all = TRUE)

ukb_data <- 
  ukb_data |> 
  separate(meaning,  c("Assay", "Meaning")) |>
  select(eid, Assay, NPX = result)


olink_targets <-  import_df("data/overlap_olink_platforms.csv")
```

# UKB

## Load data exported from UKB-RAP

```{r}

```

## Time to diagnosis

```{r}
# Add n label
ukb_meta |> 
  mutate(time_to_diagnosis = Cancer_age_diagnosis - Age_sample_collect,
         Cancer_name = ifelse(Cancer_name %in% c("Colon_cancer", "Rectum_cancer"), "Colorectal_cancer", Cancer_name)) |> 
  ggplot(aes(time_to_diagnosis)) +
  geom_histogram(fill = pal_class["Cancer"]) +
  geom_vline(xintercept = 0) +
  scale_fill_viridis_c() +
  #geom_text(aes(label = n), vjust = -0.5) +
  facet_wrap(~Cancer_name, nrow = 1, scales = "free_y") +
  theme_hpa() +
  xlab("Time to diagnostis") +
  ylab("n")


ggsave(savepath("age_ukb.png"), h = 5, w = 15)


ukb_dat <- 
  ukb_meta |> 
  mutate(time_to_diagnosis = Age_sample_collect - Cancer_age_diagnosis,
         Cancer_name = ifelse(Cancer_name %in% c("Colon_cancer", "Rectum_cancer"), "Colorectal_cancer", Cancer_name),
         Group = case_when(time_to_diagnosis <= -7 ~ "> 7 years before",
                           time_to_diagnosis > -7 & time_to_diagnosis <= -5 ~ "5-7 years before",
                           time_to_diagnosis > -5 & time_to_diagnosis <= -3 ~ "3-5 years before",
                           time_to_diagnosis > -3 & time_to_diagnosis <= -1 ~ "1-3 years before",
                           time_to_diagnosis > -1 & time_to_diagnosis <= 1 ~ "1 year before/after",
                           time_to_diagnosis > 1 & time_to_diagnosis <= 3 ~ "1-3 years after",
                           time_to_diagnosis > 3 ~ "> 3 years after"),
         Group = factor(Group, levels = names(pal_ukb_2[-1]))) |> 
  filter(!time_to_diagnosis > 20) 

ukb_cancers <- c(
                 "Colorectal_cancer",
                 "Lung_cancer",
                 "Ovary_cancer",
                 #"Pancreas_cancer",
                 "Prostate_cancer"
                 )

ukb_dat |> 
  filter(Cancer_name %in% ukb_cancers) |> 
  mutate(Cancer_name = factor(Cancer_name, levels = ukb_cancers)) |> 
  ggplot(aes(time_to_diagnosis, fill = Group)) +
  geom_histogram() +
  geom_vline(xintercept = 0) +
  scale_fill_manual(values = pal_ukb_2) +
  facet_wrap(~Cancer_name, nrow = 1, scales = "free_y") +
  theme_hpa() +
  ggtitle("") +
  xlab("Time to diagnosis")
  

ggsave(savepath_results("Publication-figures","age_ukb.pdf"), h = 4.5, w = 16)
```
## Examples

```{r}
# Examples
selected_cancers <- 
  c("Lung cancer",
    "Colorectal cancer",
    "Pancreatic cancer",
    "Prostate cancer",
    "Ovarian cancer")

top_prots <- 
  combined_de |> 
  filter(Disease %in% selected_cancers,
         Control == "All other diseases") |> 
  group_by(Disease) |> 
  top_n(1, -adj.P.Val) |> 
  ungroup() |> 
  mutate(Cancer_name = case_when(Disease == "Pancreatic cancer" ~ "Pancreas_cancer",
                                  Disease == "Prostate cancer" ~ "Prostate_cancer",
                                  Disease == "Lung cancer" ~ "Lung_cancer",
                                  Disease == "Colorectal cancer" ~ "Colorectal_cancer"))  |> 
  filter(Assay != "MMP12")

resource_data %>%
  left_join(resource_meta |> 
              select(DAid, Disease, Class), by = "DAid") |> 
  filter(Assay %in% top_prots$Assay) %>% 
  mutate(Disease = factor(Disease, levels = disease_class_order)) |> 
  ggplot(aes(Disease, NPX, color = Class, fill = Class)) +
  geom_quasirandom( size = 0.5, show.legend = F, alpha = 0.7) +
  geom_boxplot(alpha = 0.3, color = "black", outlier.colour = NA, show.legend = F) +
  scale_color_manual(values = pal_class) +
  scale_fill_manual(values = pal_class) +
  facet_wrap(~Assay, nrow = 1, scales = "free_y") +
  xlab("") +
  ylab("Protein expression") +
  coord_flip() +
  theme_hpa(angled = T, axis_y = F) 
      
ggsave(savepath("examples_proteins.pdf"), h = 15, w = 10)


ukb_dat |> 
  left_join(ukb_meta, by = c("DAid" = "eid"))  |> 
  mutate(time_to_diagnosis = Age_sample_collect - Cancer_age_diagnosis,
         Cancer_name = ifelse(Cancer_name %in% c("Colon_cancer", "Rectum_cancer"), "Colorectal_cancer", Cancer_name),
         Group = case_when(time_to_diagnosis <= -7 ~ "> 7 years before",
                           time_to_diagnosis > -7 & time_to_diagnosis <= -5 ~ "5-7 years before",
                           time_to_diagnosis > -5 & time_to_diagnosis <= -3 ~ "3-5 years before",
                           time_to_diagnosis > -3 & time_to_diagnosis <= -1 ~ "1-3 years before",
                           time_to_diagnosis > -1 & time_to_diagnosis <= 1 ~ "1 year before/after",
                           time_to_diagnosis > 1 & time_to_diagnosis <= 3 ~ "1-3 years after",
                           time_to_diagnosis > 3 ~ "> 3 years after"),
         Group = factor(Group, levels = names(pal_ukb_2[-1]))) |> 
  inner_join(top_prots |> 
               select(Cancer_name, Assay),
             by = c("Cancer_name",
                    "Assay")
                      ) |> 
#  filter(Assay %in% top_prots$Assay) |> 
  ggplot(aes(Group, NPX, color = Group, fill = Group)) +
  geom_quasirandom(alpha = 0.8, size = 0.5) +
  geom_boxplot(outlier.color = NA, alpha = 0.4, color = "black", ) +
#  stat_summary(fun = mean, geom = "point", shape = 95, size = 6, color = "black") +
  facet_wrap(Cancer_name~Assay, scales = "free_y", nrow = 1) +
  scale_color_manual(values = pal_ukb_2) +
  scale_fill_manual(values = pal_ukb_2) +
  theme_hpa(angled = T, axis_x = F)+
  xlab("") 


ggsave(savepath("ukb_examples_proteins.pdf"), h = 3, w = 13)
```


## Differential expression

```{r}

a <- 
  ukb_data |>
  filter(!Assay == "HLA") |> 
  inner_join(ukb_dat |> 
  filter(Cancer_name == cancer) |> 
  select(eid, time_to_diagnosis)) |> 
    mutate(eid = as.character(eid))

somehow_dupps <- 
  a |> 
  count(eid) |> 
  arrange(-n) |> 
  filter(n > 2000)

cancer <- "Ovary_cancer"

de_ukb <- 
  map_df(c("Colorectal_cancer", "Lung_cancer", "Ovary_cancer", "Prostate_cancer"), function(cancer) {
  
  join_data <<- 
  ukb_data |>
  filter(!Assay == "HLA") |> 
  inner_join(ukb_dat |> 
  filter(Cancer_name == cancer) |> 
  select(eid, time_to_diagnosis)) |> 
    mutate(eid = as.character(eid)) |> 
 #mutate(Sex = factor(Sex)) |> 
  filter(time_to_diagnosis < 1,
         !eid %in% somehow_dupps$eid) |> 
  pivot_wider(names_from = "Assay", values_from = "NPX") |> 
    rename(DAid = eid)

do_limma_continuous(join_data = join_data,
                    variable = "time_to_diagnosis",
                    correct = c(),
                   correct_type = c(),
                    pval_lim = 0.05,
                    logfc_lim = 0) |> 
  mutate(Cancer_name = cancer) 
})

de_ukb |> count(Cancer_name)
```

## Volcano plots

```{r}

labels <- 
  de_ukb |> 
  group_by(Cancer_name) |> 
  top_n(6, -adj.P.Val) |> 
  filter(sig != " not significant")

de_ukb |> 
  ggplot(aes(x = logFC, y = -log10(adj.P.Val), color = sig, label = Assay)) +
  geom_point(size = 1, alpha = 0.4) + 
  geom_text_repel(data = labels, size = 2, show.legend = F) +
  geom_hline(yintercept = -log10(0.05), linetype = 'dashed', color = "darkgrey") +
 # geom_vline(xintercept = -cutoff, linetype = 'dashed', color = "darkgrey") +
#  geom_vline(xintercept = cutoff, linetype = 'dashed', color = "darkgrey") +
  scale_color_manual(values = pal_de) +
  facet_wrap(~Cancer_name, scales = "free", nrow = 1) +
  theme_hpa() +   
  theme(axis.text = element_text(size = 8),
        legend.position = "right") +
  xlab("Model coefficient")

ggsave(savepath_results("Publication-figures", "ukb_de.pdf"), h = 3, w = 12)
```

## Proteins

```{r}

plot_nefl <- boxplot_ukb("Lung_cancer", "NEFL") 
#plot_cxcl8 <- boxplot_ukb("Colorectal_cancer", "CXCL8") 
plot_ceacam5 <- boxplot_ukb("Lung_cancer", "CEACAM5") 
plot_areg <-   boxplot_ukb("Colorectal_cancer", "AREG")
#plot_areg_lung <-   boxplot_ukb("Lung_cancer", "AREG")
plot_crc <- boxplot_ukb("Colorectal_cancer", "C1QA")
#plot_areg_lung <-   boxplot_ukb("Lung_cancer", "AREG")
#boxplot_ukb("Prostate_cancer", "KLK4")
plot_ovary <- boxplot_ukb("Ovary_cancer", "WFDC2")

boxplot_ukb("Prostate_cancer", "AREG")

plot_ceacam5 | plot_nefl | plot_crc | plot_areg | plot_ovary
ggsave(savepath_results("Publication-figures", "examples_ukp.pdf"), h = 3, w = 14)

protein <- 
cancer <- 

protein <- "CXCL8"
cancer <- "Colorectal_cancer"

protein <- "VTCN1"
cancer <- "Ovary_cancer"



ggsave(savepath("TFRC.png"), h = 4, w = 5)
ggsave(savepath("MDK_mockup.png"), h = 3, w = 4)
```


## Plot two examples

```{r}
protein <- "AGR2"

hdba_data |> 
  left_join(hdba_meta, by = "DAid") |>
  filter(Assay == protein,
         Disease %in% c("Ovarian cancer", 
                        "Breast cancer", 
                        "Prostate cancer",
                        "Lung cancer",
                        "Colorectal cancer")) |> 
  ggplot(aes(Disease, NPX, color = Disease, fill = Disease)) +
  geom_quasirandom() +
  geom_boxplot(outlier.color = NA, alpha = 0.4, color = "black") +
  scale_color_manual(values = (pal_ucan_2)) +
  scale_fill_manual(values = (pal_ucan_2)) +
  theme_hpa(axis_x = F)

ggsave(savepath("AGR2_P1.png"), h = 4, w = 5)
ggsave(savepath("CEACAM5_P1.png"), h = 4, w = 5)

ucan_data |> 
  left_join(manifest, by = "DAid") |>
  filter(Assay == protein,
         Diagnose %in% names(pal_ucan)) |> 
  ggplot(aes(Diagnose, NPX, color = Diagnose, fill = Diagnose)) +
  geom_quasirandom() +
  geom_boxplot(outlier.color = NA, alpha = 0.4, color = "black") +
  scale_color_manual(values = (pal_ucan)) +
  scale_fill_manual(values = (pal_ucan)) +
  theme_hpa(axis_x = F)

ggsave(savepath("CEACAM5_P2.png"), h = 4, w = 5)
ggsave(savepath("AGR2_P2.png"), h = 4, w = 5)





protein <- "PAEP"

hdba_data |> 
  left_join(hdba_meta, by = "DAid") |>
  filter(Assay == protein,
         Disease %in% c("Ovarian cancer", 
                        "Breast cancer", 
                        "Prostate cancer",
                        "Lung cancer",
                        "Colorectal cancer")) |> 
  ggplot(aes(Disease, NPX, color = Disease, fill = Disease)) +
  geom_quasirandom(show.legend = F) +
  geom_boxplot(outlier.color = NA, alpha = 0.4, color = "black", show.legend = F) +
  scale_color_manual(values = (pal_ucan_2)) +
  scale_fill_manual(values = (pal_ucan_2)) +
  theme_hpa() +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank()) +
  xlab("Cancers") +
  ylab("Protein expression")

ggsave(savepath("PAEP_P1.png"), h = 4, w = 4)

ucan_data |> 
  left_join(manifest, by = "DAid") |>
  filter(Assay == protein,
         Diagnose %in% names(pal_ucan)) |> 
  ggplot(aes(Diagnose, NPX, color = Diagnose, fill = Diagnose)) +
  geom_quasirandom(show.legend = F) +
  geom_boxplot(outlier.color = NA, alpha = 0.4, color = "black", show.legend = F) +
  scale_color_manual(values = (pal_ucan)) +
  scale_fill_manual(values = (pal_ucan)) +
  theme_hpa() +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank()) +
  xlab("Cancers") +
  ylab("Protein expression")

ggsave(savepath("PAEP_P2.png"), h = 4, w = 4)

```
